spring:
  #jsp
  mvc:
    devtools:
      livereload:
        enabled: true
    static-path-pattern: /resources/**
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
      location: /home/purple

  #jdbc 설정
  datasource:
    url: jdbc:mysql://localhost:3306/purple?autoReconnect=true
    username: purple
    password: koreait2020
    driver-class-name: com.mysql.cj.jdbc.Driver

  #소셜로그인
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 223590531622-gapoulh2bi9ha2sou8ac0q0hbik1fmjr.apps.googleusercontent.com
            client-secret: W_3fa8LILuklW2Ys9oPnCSry
          facebook:
            client-id: 453108009137161
            client-secret: 185f9f7c745e78cf61ae77811d6a2325

custom:
  oauth2:
    kakao:
      client-id: dcd77beafc72e48753f0d5c6a3de7357
      client-secret: fje5GZ41eNxENmpXLohtA1TsboD7LiGJ
    naver:
      client-id: FncvzBqJPltRANb9yYrk
      client-secret: VB2Af9_gWS

#myBatis 설정
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.purple.demo.model

#Tomcat
server:
  port: 80

  # ssl 적용
  # ssl:
  #   enabled: true
  #   key-alias: purplestore
  #   key-store: purplestore
  #   key-store-password: 'purple'
  #   key-password: 'purple'
  #   trust-store: purpletrust
  #   trust-store-password: 'purple'
