spring:
  #jsp
  mvc:
    devtools:
      livereload:
        enabled: true
    static-path-pattern: /resources/**
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  #jdbc 설정
  datasource:
    url: jdbc:mysql://localhost:3307/purple?autoReconnect=true
    username: root
    password: koreait2020
    driver-class-name: com.mysql.cj.jdbc.Driver

#myBatis 설정
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.purple.demo.model

#Tomcat
server:
  port: 8090
  multipart:
    max-file-size: 50MB
    max-request-size: 50MB

  ssl:
    enabled: true
    key-alias: purplestore
    key-store: purplestore
    key-store-password: 'purple'
    key-password: 'purple'
    trust-store: purpletrust
    trust-store-password: 'purple'
#이미지
